apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ template "application.namespace" . }}
  labels:
    {{- include "application.defaultLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "application.defaultLabels" . | nindent 8 }}
      annotations:
        configmap-hash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              cp /app/config/nsecbunker.json {{ .Values.config_file }}
              npx prisma migrate deploy
          env:
            - name: DATABASE_URL
              value: "file:{{ .Values.database_file }}"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/nsecbunker.json
              subPath: nsecbunker.json
            - name: data-volume
              mountPath: /app/data
      containers:
        - name: bunker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
            - dist/index.js
            - start
            - -c
            - {{ .Values.config_file }}
          env:
            - name: DATABASE_URL
              value: "file:{{ .Values.database_file }}"
            - name: ADMIN_NPUBS
              value: "{{ .Values.adminNPubs | join "," }}"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "application.fullname" . }}-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "application.fullname" . }}-data
