apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-dvms
  namespace: {{ template "application.namespace" . }}
  labels:
    {{- include "application.defaultLabels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.dvms }}
  {{ $key }}.py: |
{{ $value | indent 4 }}
{{- end }}
