{{ if eq .Values.configMap.database.engine "sqlite" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.fullname" . }}-data
  namespace: {{ template "application.namespace" . }}
  labels:
    {{- include "application.defaultLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sqlite.pvClaim.size }}
{{ end }}
