apiVersion: v2
description: A Helm chart for Kubernetes to deploy the nostr-rs-relay application
type: application
maintainers:
  - name: nourspace
    email: info@nour.space
name: nostr-rs-relay
sources:
  - https://github.com/nostr-community/helm-charts
  - https://github.com/scsibug/nostr-rs-relay
version: 0.1.0
appVersion: latest
kubeVersion: ">=1.19.0-0"
home: https://github.com/scsibug/nostr-rs-relay/tags
keywords:
  - nostr
  - relay
  - rust
