apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ template "application.namespace" . }}
  labels:
    {{- include "application.defaultLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "application.defaultLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 100
      containers:
        - name: relay
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python
            - cli.py
            {{- range .Values.dvms_list }}
            - "{{ . }}"
            {{- end }}
          env:
            - name: NOSTR_ADMIN
              value: "{{ .Values.env.NOSTR_ADMIN }}"
            - name: NOSTR_RELAYS
              value: "{{ .Values.env.NOSTR_RELAYS }}"
          volumeMounts:
            - name: dvms-volume
              mountPath: /app/dvms
      volumes:
        - name: dvms-volume
          configMap:
            name: {{ include "application.fullname" . }}-dvms
